services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: ipard_api
    volumes:
      - ./ipard_rag/src:/app
      - ./ipard_rag/data:/app/data
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped

  ui:
      build:
        context: .
        dockerfile: Dockerfile.ui
      container_name: ipard_ui
      volumes:
        # /app/src/app.py yerine /app/app.py yaparak Dockerfile ile eşledik
        - ./ipard_rag/src/app.py:/app/app.py
      env_file:
        - .env
      environment:
        - API_URL=http://api:8000
      ports:
        - "8501:8501"
      depends_on:
        - api
      restart: unless-stopped