FROM python:3.11-slim
WORKDIR /app
COPY ipard_rag/requirements-ui.txt .
RUN pip install --no-cache-dir -r requirements-ui.txt
# app.py'yi direkt /app altına kopyalıyoruz
COPY ipard_rag/src/app.py .
ENV PYTHONUNBUFFERED=1
EXPOSE 8501
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0", "--server.headless=true"]